### ISSUE TITLE
New function suggestion

### ISSUE THREAD

**Issue by bestruirui** [JGeek00/my-server-status-api#1]
- Deploy using docker
- Support monitoring and control docker container.

**Comment by JGeek00** [comment]
Sorry but this API cannot be executed inside a container because it requires full access to the hardware, but the option to monitor docker containers I think is actually a good idea.

**Comment by bestruirui** [comment]
Thank you for your reply.
About obtaining system information, I think we can refer to the deployment method of netdata.
Map the corresponding files into the container in Linux system.
```
docker run -d --name=netdata
-p 19999:19999
-v netdataconfig:/etc/netdata
-v netdatalib:/var/lib/netdata
-v netdatacache:/var/cache/netdata
-v /etc/passwd:/host/etc/passwd:ro
-v /etc/group:/host/etc/group:ro
-v /proc:/host/proc:ro
-v /sys:/host/sys:ro
-v /etc/os-release:/host/etc/os-release:ro 
--restart unless-stopped 
--cap-add SYS_PTRACE 
--security-opt apparmor=unconfined 
netdata/netdata
```

**Comment by JGeek00** [comment]
@bestruirui on version 1.3.0-beta.3 of the application I added a new screen for the Docker information. You will need also to update the API on your server to version 1.2.0 on the developer branch

**Comment by bestruirui** [comment]
thankyou
