### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by MeowIce** [JGeek00/my-server-status-api#2]
- Push notification when disk(s) full.
- Show system uptime on the Home page.
- maybe...hide the server address on the Home page, just server name.
- Show pending updates ?

**Comment by JGeek00** [comment]
Hi. Thanks for your suggestions.

- Push notifications: don't know if I can do that, I would have to check it
- System uptime: I will add it
- Hide server address: I will add a toggle on the app settings to hide it
- pending updates: I was already thinking about adding some system to display a modal when there's an update available for the server API

**Comment by shandongtlb** [comment]
How to enable https in api?
At present, the only method may be nginx reverse proxy. For security reasons, can you add the function of specifying a listening IP, such as listen 127.0.0.1, and then use nginx reverse proxy, so that you can access only through https?

**Comment by JGeek00** [comment]
@shandongtlb I will investigate how to listen only on a certain IP.

**Comment by shandongtlb** [comment]
Thank you very much, keep it up!

**Comment by JGeek00** [comment]
System uptime and IP addresses restriction are added on API v1.3.0.
Hide server address has to be added on the app.
The rest won't be implemented because this is the last build for this project, as it's discontinued.
